"""empty message

Revision ID: dd7c9b471a69
Revises: 
Create Date: 2019-01-30 14:52:00.264209

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from scheduler.models import AlertStatus, AlertDetail

# revision identifiers, used by Alembic.
revision = 'dd7c9b471a69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(AlertStatus.ALERT_STATUSES), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('service_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alert',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('alert_id', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_table('user_level',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('level_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_detail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_level_id', sa.INTEGER(), nullable=True),
    sa.Column('call_status', sqlalchemy_utils.types.choice.ChoiceType(AlertDetail.CALL_STATUSES), nullable=True),
    sa.Column('response', sa.String(length=512), nullable=True),
    sa.Column('call_reference_id', sa.String(length=512), nullable=True),
    sa.Column('alert_id', sa.String(length=128), nullable=False),
    sa.Column('alert_status_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['alert_status_id'], ['alert_status.id'], ),
    sa.ForeignKeyConstraint(['user_level_id'], ['user_level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_reference_id')
    )
    op.create_index(op.f('ix_alert_detail_alert_id'), 'alert_detail', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_detail_alert_id'), table_name='alert_detail')
    op.drop_table('alert_detail')
    op.drop_table('user_level')
    op.drop_table('alert')
    op.drop_table('users')
    op.drop_table('service')
    op.drop_table('alert_status')
    # ### end Alembic commands ###
